# Generated by Django 2.0.2 on 2018-02-13 11:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_detail',
            new_name='product_detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_pub_date',
            new_name='product_pub_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='products_stars',
            new_name='product_stars',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='viewers',
            new_name='viewer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='stores_name',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='stores_stars',
            new_name='store_stars',
        ),
    ]
